# Generated by Django 5.2.7 on 2025-10-09 07:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=100, verbose_name='Titre du bandeau')),
                ('image_banner', models.ImageField(upload_to='banner_images', verbose_name='Image du bandeau')),
                ('description', models.TextField(verbose_name='Description')),
                ('banner_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix du bandeau')),
            ],
            options={
                'verbose_name': 'Bandeau',
                'verbose_name_plural': 'Bandeaux',
            },
        ),
        migrations.CreateModel(
            name='BestSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix actuel')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix original')),
                ('bestseller_image', models.ImageField(blank=True, null=True, upload_to='bestseller_images', verbose_name='Image BestSeller')),
            ],
            options={
                'verbose_name': 'Meilleure vente',
                'verbose_name_plural': 'Meilleures ventes',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blogs', verbose_name='Image du blog')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('signature', models.CharField(blank=True, help_text='(By Mr Admin / August 24, 2025)', max_length=75, null=True, verbose_name='Signature')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Cta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta_discount', models.CharField(max_length=25, verbose_name='Remise CTA')),
                ('cta_title', models.CharField(max_length=25, verbose_name='Titre CTA')),
                ('cta_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix CTA')),
                ('cta_image', models.ImageField(upload_to='cta_images', verbose_name='Image CTA')),
            ],
            options={
                'verbose_name': 'CTA',
                'verbose_name_plural': 'CTAs',
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Abonné le')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Liste des abonnés',
            },
        ),
        migrations.CreateModel(
            name='Toast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='(Nom du dernier produit vendu)', max_length=100, verbose_name='Nom')),
                ('toast_image', models.ImageField(upload_to='toast_images', verbose_name='Image du toast')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Toast',
                'verbose_name_plural': 'Toasts',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Clé de session')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('category_image', models.FileField(blank=True, null=True, upload_to='vectore_images', verbose_name='Image de la catégorie')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category', verbose_name='Parent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Clé de session')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('address', models.CharField(max_length=100, verbose_name='Adresse')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Code postal')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('canceled', 'Annulée')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total payé')),
                ('paid', models.BooleanField(db_index=True, default=False, verbose_name='Payé')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID de transaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('subname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sous-nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix actuel')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix original')),
                ('badge', models.CharField(blank=True, max_length=25, null=True, verbose_name='Badge')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('thumbnail', models.ImageField(upload_to='products', verbose_name='Image miniature')),
                ('scroll_image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Image défilante')),
                ('status', models.CharField(blank=True, choices=[('new', 'Nouveauté'), ('on_sale', 'Promotion'), ('flash_sale', 'Vente flash'), ('best_seller', 'Meilleure vente'), ('limited', 'Stock limité'), ('back_in_stock', 'De retour en stock'), ('preorder', 'Précommande'), ('sold_out', 'Rupture de stock')], db_index=True, max_length=25, null=True, verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('add_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date d'ajout")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Commande')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Produit commandé',
                'verbose_name_plural': 'Produits commandés',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart', verbose_name='Panier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article du panier',
                'verbose_name_plural': 'Articles du panier',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valeur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='store.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Caractéristique de produit',
                'verbose_name_plural': 'Caractéristiques de produit',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='galerie', verbose_name='Image')),
                ('legende', models.CharField(blank=True, max_length=100, null=True, verbose_name='Légende')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Miniature de produit',
                'verbose_name_plural': 'Miniatures de produit',
            },
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Clé de session')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='store.product', verbose_name='Produit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Like de produit',
                'verbose_name_plural': 'Likes de produits',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code promo')),
                ('discount_percentage', models.PositiveIntegerField(help_text='La réduction en pourcentage', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage de réduction')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'start_date', 'end_date'], name='store_promo_is_acti_12f1c8_idx')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.promocode'),
        ),
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='store.promocode'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('promotion_image', models.ImageField(blank=True, null=True, upload_to='deal_images', verbose_name='Image de la promotion')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix actuel')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix original')),
                ('already_sold', models.PositiveIntegerField(default=0, verbose_name='Déjà vendu')),
                ('available', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='store_promo_start_d_233727_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review & Rating',
                'verbose_name_plural': 'Reviews & Ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', '-add_date'], name='store_produ_status_afb80b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='productlike',
            unique_together={('product', 'user', 'session_key')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewrating',
            unique_together={('product', 'user')},
        ),
    ]
