# Generated by Django 5.2.7 on 2025-10-09 07:48

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre de la page')),
                ('slug', models.SlugField(help_text="Identifiant unique utilisé pour lier le contenu au lien du footer. Doit correspondre à l'ID du lien HTML.", max_length=100, unique=True, verbose_name='Identifiant (slug)')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenu de la page')),
            ],
            options={
                'verbose_name': 'Information Légale',
                'verbose_name_plural': 'Informations Légales',
            },
        ),
    ]
